### ISSUE TITLE
Result::unwrap()` on an `Err` value: Error(JsValue(Error: missing field `ctxt`

### ISSUE THREAD

**Issue by joshjhargreaves** [kwonoj/woodpile#16]
Thanks for making the project, I'm looking forward to working with it! I'm just trying to run the demo and I get the following error.
```
panicked at packages/woodpile/src/lib.rs:55:60:
called `Result::unwrap()` on an `Err` value: Error(JsValue(Error: missing field `ctxt`
Error: missing field `ctxt`
    at module.exports.__wbindgen_error_new (XXXX/node_modules/woodpile/packages/woodpile/pkg/woodpile.js:452:17)
    at wasm://wasm/0143cea2:wasm-function[2124]:0x4bee97
    at wasm://wasm/0143cea2:wasm-function[3122]:0x4f3061
    at wasm://wasm/0143cea2:wasm-function[620]:0x37015b
    at wasm://wasm/0143cea2:wasm-function[189]:0x218730
    at wasm://wasm/0143cea2:wasm-function[417]:0x2fb2b9
    at module.exports.visit (XXXX/woodpile/packages/woodpile/pkg/woodpile.js:218:22)
    at file:///XXXX/demo.mjs:10:1
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)))

Stack:

Error
    at module.exports.__wbg_new_abda76e883ba8a5f (XXXX/node_modules/woodpile/packages/woodpile/pkg/woodpile.js:319:17)
    at wasm://wasm/0143cea2:wasm-function[2802]:0x4e6aba
    at wasm://wasm/0143cea2:wasm-function[3358]:0x4f89bd
    at wasm://wasm/0143cea2:wasm-function[3011]:0x4efdad
    at wasm://wasm/0143cea2:wasm-function[417]:0x2fb415
    at module.exports.visit (XXXX/node_modules/woodpile/packages/woodpile/pkg/woodpile.js:218:22)
    at file:///XXXXX/demo.mjs:10:1
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
   ```
   
   
   ```json
"@swc/core": "1.7.10",
"woodpile": "0.0.6"
```
 node version: v21.7.3

```js
import { parseSync } from '@swc/core';
import { visit } from "woodpile";

const ast = parseSync('console.log("Hello, World!")');

visit(ast, {
    visit: {
        // Callbacks with visit${NodeName} will be called recursively for the node
        visitProgram: (node, self) => {
            console.log('visitProgram', node);
        },
        visitExpr: (node) => {
            console.log('visitExpr', node);
        }
    },
});
```

**Comment by Xiot** [comment]
I just ran into the same thing.  
Downgrading `@swc/core` to `1.3.71` made it work, so it looks like there was a compatibility break somewhere.
